### ISSUE TITLE
pug get error on meta ^1.11.0

### ISSUE THREAD

**Issue by larry-cariq** [superakabo/dlibphonenumber#2]
@superakabo 
Thanks for this package. It is very useful and is nice that it does not contain any platform plugins.

I am seeing `pub get` error using the latest flutter_test and:
```
Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (7 days ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5
```

Error:
_Because every version of flutter_test from sdk depends on meta 1.10.0 and dlibphonenumber >=1.1.3 depends on meta ^1.11.0, flutter_test from sdk is incompatible with dlibphonenumber >=1.1.3.
So, because cariq_ui depends on both dlibphonenumber ^1.1.7 and flutter_test from sdk, version solving failed._

Is it possible to downgrade meta from 1.11.0 to 1.10.0?

**Comment by superakabo** [comment]
Hi @larry-cariq 
You can override meta in your project by adding this to your pubspec.yaml file.
```dart
dependency_overrides:
  meta: ^1.11.0 # or 1.10.0
```

**Comment by larry-cariq** [comment]
Thanks, that worked.

**Comment by larry-cariq** [comment]
@superakabo This is a very useful package. You should setup the publisher on pub.dev  since it looks like this: 
```
Publisher
unverified uploader
```

**Comment by superakabo** [comment]
> @superakabo This is a very useful package. You should setup the publisher on pub.dev since it looks like this:
> 
> ```
> Publisher
> unverified uploader
> ```

Sure. I'll do that soon.
Thanks.
