### ISSUE TITLE
Metadata source 

### ISSUE THREAD

**Issue by tolotrasamuel** [superakabo/dlibphonenumber#4]
Thank you for creating and maintaining this awesome lib. Out of curiosity, where do you source all the metadata ? I see that you are using a code generator but there is no mention about this code generator in the repo, how can others who want to contribute get access to it ?

**Comment by superakabo** [comment]
Hi @tolotrasamuel,
This project uses the metadata from libphonenumber. 
It is automatically updated when there is a new release from the source. 
As such, metadata contributions should be made at the source - [libphonenumber](https://github.com/google/libphonenumber) for consistency. 
You can read more about it from here [Contributing to libphonenumber](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md)
